minor reformatting, and java files dynamically choose their classname instead of the default class Code classname

diff --git a/codetempl b/codetempl
--- a/codetempl
+++ b/codetempl
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+function file_extension() {
+	echo $1 | sed 's/^[^\.]*\.//g'
+}
+
 if [ -z $1 ]; then echo 'no file name or language entered'; exit; fi
 
 valid_languages='python c java bash cpp html'
@@ -24,32 +28,25 @@ do
 		language=$entry
 		case $language in
 		"python")
-			ext='.py'
-			contents=$python_file
+			ext='.py'; contents=$python_file
 			;;
 		'c')
-			ext='.c'
-			contents=$c_file
+			ext='.c'; contents=$c_file
 			;;
 		'java')
-			ext='.java'
-			contents=$java_file
+			ext='.java'; contents=$java_file
 			;;
 		'bash')
-			ext='.sh'
-			contents=$bash_file
+			ext='.sh'; contents=$bash_file
 			;;
 		'cpp')
-			ext='.cpp'
-			contents=$cpp_file
+			contents=$cpp_file; ext='.cpp'
 			;;
 		'html')
-			ext='.html'
-			contents=$html_file
+			contents=$html_file; ext='.html'
 			;;
 		*)
-			echo 'invalid language: '$language
-			exit 1
+			echo 'invalid language: '$language; exit 1
 			;;
 		esac
 
@@ -59,30 +56,22 @@ do
 	then
 		echo "going of filename"
 		filename=$entry
-		ext=$(echo $filename | sed 's/^[^.]*\.//')
+		ext=$( file_extension $filename )
 		case $ext in
 		'py')
-			contents=$python_file
-			;;
+			contents=$python_file	;;
 		'c')
-			contents=$c_file
-			;;
+			contents=$c_file	;;
 		'java')
-			contents=$java_file
-			;;
+			contents=$java_file	;;
 		'sh')
-			contents=$bash_file
-			;;
+			contents=$bash_file	;;
 		'cpp')
-			contents=$cpp_file
-			;;
+			contents=$cpp_file	;;
 		'html')
-			contents=$html_file
-			;;
+			contents=$html_file	;;
 		*)
-			echo 'invalid filename: '$filename
-			exit 1
-			;;
+			echo 'invalid filename: '$filename; exit 1	;;
 		esac
 	else
 		echo "invalid input: "$entry
@@ -90,7 +79,22 @@ do
 	fi
 
 	if [ ! -f $filename  ]
-	then echo "none exist. will make"; cp $contents $filename
-	else echo "file '$filename' already exists. try again with new name"
+	then
+		echo "none exist. will make"
+		cp $contents $filename
+		if [ $(file_extension $filename) = 'java' ]
+		then
+			sed -i "s/class Code/class ${filename//.java/}/" $filename 
+		fi
+	else
+		echo "file '$filename' already exists"
 	fi
+
+
 done
+
+
+
+
+
+
